default: help

.PHONY: help
venv: venv_projet_nhl/bin/activate # activate venv
	source venv_projet_nhl/bin/activate

see_config_train: # see hydra conf of file Milestone2/training_main.py
	python3 Milestone2/training_main.py --cfg job > /tmp/toto.yaml && yq /tmp/toto.yaml

see_config_hp_opt: # see hydra conf of file Milestone2/hp_opt_main.py
	python3 Milestone2/hp_opt_main.py --cfg job > /tmp/toto.yaml && yq /tmp/toto.yaml

clean: # clean all the files generated by the training
	rm -rf log_file outputs training_artifacts multirun

run_baseline: # run baseline model XGBoost & Logistice Regression with default args on dist&angle features
	python3 Milestone2/training_main.py --multirun model=logistic_regression,xgboost model.run_with_default_args=True

# TOFIX
del_bp:
	for i in $(ag 'pdb.set_trace()' -l); do sed -i '/pdb.set_trace()/d' $i; done

help: # Show help for each of the Makefile recipes.
	@grep -E '^[a-zA-Z0-9 -_]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done

