FROM python:3.8
ARG PORT=1234
ENV PORT=${PORT}

WORKDIR /code

# Add files
COPY ./serving/ ./

# install libs
RUN pip install --upgrade pip
RUN pip install -r ./requirements_backend.txt

RUN pip install gunicorn

CMD gunicorn --bind 0.0.0.0:${PORT} app:app

# expose ports
EXPOSE ${PORT}